const state={config:null,fileName:'Devices.json',active:'overview',dirty:false};
const sections=[['overview','⌂','Übersicht'],['host','◌','Host-Konfiguration'],['devices','▣','Geräte'],['axes','↔','Achsen & Kollision'],['startup','≡','Startup-Reihenfolge'],['assemblies','◇','Assemblies']];
const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const enumOptions={
  RotationDegrees:[-90,0,90],
  Encoder:['Jpeg','NvencH264'],
  RemoteAccess:['None','ReadOnly','Full'],
  SecurityMode:['None','Sign','SignAndEncrypt'],
  AuthenticationMode:['Anonymous','UserName'],
  DataType:['Boolean','Byte','SByte','Int16','UInt16','Int32','Int64','UInt32','UInt64','Float','Double','String'],
  Access:['ReadOnly','ReadWrite']
};
function markDirty(){state.dirty=true;$('#dirtyState').classList.remove('hidden');$('#statusDot')?.classList.add('dirty')}
function setValue(path,value){let o=state.config;for(let i=0;i<path.length-1;i++)o=o[path[i]];o[path.at(-1)]=value;markDirty()}
function input(path,value,opts={}){const property=path.at(-1);const options=enumOptions[property];const type=typeof value==='boolean'?'checkbox':typeof value==='number'?'number':'text';const label=opts.label||property;const checked=type==='checkbox'?(value?'checked':''):'';const step=type==='number'?'step="any"':'';const control=options?`<select data-path="${path.join('.')}">${options.map(option=>`<option value="${esc(option)}" ${String(option)===String(value)?'selected':''}>${esc(option)}</option>`).join('')}</select>`:`<input data-path="${path.join('.')}" type="${type}" value="${type==='checkbox'?'':esc(value)}" ${checked} ${step} ${opts.placeholder?`placeholder="${esc(opts.placeholder)}"`:''}/>`;return `<div class="field ${type==='checkbox'?'checkbox':''}"><label>${esc(label)}</label>${control}${opts.help?`<small>${esc(opts.help)}</small>`:''}</div>`}
function panel(title,intro,body){return `<section class="section-panel"><h2>${title}</h2><p class="panel-intro">${intro}</p>${body}</section>`}
function overview(){const c=state.config;const count=(k)=>Array.isArray(c[k])?c[k].length:0;return panel('Systemübersicht','Grundlegende Identität und Umfang dieser DeviceConfig.',`<div class="field-grid">${input(['SystemId'],c.SystemId,{label:'System-ID',help:'Eindeutiger Name der CT-Anlage.'})}<div class="field"><label>Konfigurationsumfang</label><div class="summary-chips"><span>${count('Detectors')} Detektor${count('Detectors')===1?'':'en'}</span><span>${count('Sources')} Quelle${count('Sources')===1?'':'n'}</span><span>${count('SystemDevices')} Systemgeräte</span></div></div></div>`)}
function host(){const h=state.config.HostConfigurations||{};const s=h.ImageStorage||{},sc=h.SessionControl||{},x=h.XFlowProvider||{},d=h.DetectorStreams||{};return panel('Host-Konfiguration','Dienste und Datenströme, die zum Maschinen-Setup gehören.',`<div class="field-grid">${input(['HostConfigurations','ImageStorage','LocalFallbackPath'],s.LocalFallbackPath,{label:'Lokaler Fallback-Pfad'})}${input(['HostConfigurations','ImageStorage','DirectBufferCapacityFrames'],s.DirectBufferCapacityFrames,{label:'Direktpuffer (Frames)'})}${input(['HostConfigurations','ImageStorage','LocalSpoolBufferCapacityFrames'],s.LocalSpoolBufferCapacityFrames,{label:'Spool-Puffer (Frames)'})}${input(['HostConfigurations','SessionControl','SessionTimeoutSeconds'],sc.SessionTimeoutSeconds,{label:'Session-Timeout (s)'})}${input(['HostConfigurations','SessionControl','CleanupIntervalSeconds'],sc.CleanupIntervalSeconds,{label:'Bereinigung (s)'})}${input(['HostConfigurations','XFlowProvider','DisplayName'],x.DisplayName,{label:'XFlow-Anzeigename'})}${input(['HostConfigurations','XFlowProvider','Address'],x.Address,{label:'XFlow-Adresse'})}${input(['HostConfigurations','XFlowProvider','MaxConcurrency'],x.MaxConcurrency,{label:'Max. Parallelität'})}${input(['HostConfigurations','XFlowProvider','Enabled'],x.Enabled,{label:'XFlow aktiviert'})}</div>${cameraFields((h.CameraStreams||{}).Cameras||[])}${streamFields(d)}`)}
function cameraFields(cameras){return `<div class="list-header"><h3>Kamera-Streams (${cameras.length})</h3></div>${cameras.map((camera,i)=>`<div class="array-card"><div class="array-card-head"><strong>${esc(camera.DisplayName||camera.ServiceId||`Kamera ${i+1}`)}</strong></div><div class="field-grid">${['ServiceId','DisplayName','Enabled','DeviceIndex','Backend','Width','Height','FramesPerSecond','JpegQuality','RotationDegrees','FlipHorizontal','FlipVertical','ReconnectDelaySeconds'].filter(f=>camera[f]!==undefined).map(f=>input(['HostConfigurations','CameraStreams','Cameras',i,f],camera[f],{label:f})).join('')}</div></div>`).join('')}`}
function streamFields(d){const p=d.Preview||{},l=d.Lossless||{};return `<div class="list-header"><h3>Detektor-Streams</h3></div><div class="field-grid">${input(['HostConfigurations','DetectorStreams','Preview','Enabled'],p.Enabled,{label:'Preview aktiviert'})}${input(['HostConfigurations','DetectorStreams','Preview','Encoder'],p.Encoder,{label:'Preview-Encoder'})}${input(['HostConfigurations','DetectorStreams','Preview','Quality'],p.Quality,{label:'Preview-Qualität'})}${input(['HostConfigurations','DetectorStreams','Preview','MaxFramesPerSecond'],p.MaxFramesPerSecond,{label:'Max. FPS'})}${input(['HostConfigurations','DetectorStreams','Lossless','Enabled'],l.Enabled,{label:'Lossless aktiviert'})}${input(['HostConfigurations','DetectorStreams','Lossless','Compression'],l.Compression,{label:'Kompression'})}${input(['HostConfigurations','DetectorStreams','Lossless','CompressionLevel'],l.CompressionLevel,{label:'Kompressionslevel'})}${input(['HostConfigurations','DetectorStreams','Lossless','IncludeChecksum'],l.IncludeChecksum,{label:'Checksum einschließen'})}</div>`}
function cards(key,title,fields){const arr=state.config[key]||[];return panel(title,`${arr.length} Einträge in der Konfiguration.`,`${arr.map((item,i)=>`<div class="array-card"><div class="array-card-head"><strong>${esc(item.DeviceId||item.ServiceId||item.Alias||`${title} ${i+1}`)}</strong><button class="link-button" data-remove="${key}.${i}">Eintrag entfernen</button></div><div class="field-grid">${fields.map(f=>input([key,i,f],item[f],{label:f})).join('')}</div></div>`).join('')||'<p class="panel-intro">Keine Einträge vorhanden.</p>'}`)}
function devices(){return cards('Detectors','Detektoren',['$type','DeviceId','ImageProcessingBackend','BitDepth','ImagePath','NumImages','ImageStep'])+cards('Sources','Quellen',['$type','DeviceId','MaxCurrent'])+cards('SystemDevices','Systemgeräte',['$type','DeviceId','RemoteAccess','DetectorId','SourceId','RotationAxisId','FodAxisId','FddAxisId','ProjectionCount'])}
function axes(){const a=state.config.AxesConfiguration||{};return panel('Achsen & Kollision','Mechanische Struktur, Controller und Kollisionsgeometrie.',`<div class="field-grid">${(a.StageControllers||[]).map((x,i)=>input(['AxesConfiguration','StageControllers',i,'DeviceId'],x.DeviceId,{label:`Controller ${i+1}` })).join('')}</div>${cardsFromNested('Axes','Axes',a.Axes||[],['$type','DeviceId','ControllerId','AxisNodeId','Movement','LimMin','LimMax','MoveAfterInit'])}${cardsFromNested('AxisNodes','AxisNodes',a.AxisNodes||[],['NodeId','DependedNodeId'])}`)}
function cardsFromNested(label,title,arr,fields){return `<div class="list-header"><h3>${title} (${arr.length})</h3></div>${arr.map((x,i)=>`<div class="array-card"><div class="array-card-head"><strong>${esc(x.DeviceId||x.NodeId||`${title} ${i+1}`)}</strong></div><div class="field-grid">${fields.map(f=>input(['AxesConfiguration',label,i,f],x[f],{label:f})).join('')}</div></div>`).join('')}`}
function startup(){const arr=state.config.Startup||[];return panel('Startup-Reihenfolge','Die Reihenfolge bestimmt, welche Geräte beim Start zuerst verfügbar sind.',arr.map((x,i)=>`<div class="array-card"><div class="field-grid">${input(['Startup',i,'DeviceId'],x.DeviceId,{label:`Position ${i+1}`})}</div></div>`).join(''))}
function assemblies(){return cards('Assemblies','Assemblies',['Assembly','Type','Alias'])}
function render(){if(!state.config){$('#emptyState').classList.remove('hidden');$('#editor').classList.add('hidden');return}$('#emptyState').classList.add('hidden');$('#editor').classList.remove('hidden');const map={overview,host,devices,axes,startup,assemblies};$('#editor').innerHTML=map[state.active]();$('#pageTitle').textContent=sections.find(s=>s[0]===state.active)[2];$('#pageDescription').textContent='Bearbeite Werte direkt in der strukturierten Ansicht.';document.querySelectorAll('[data-path]').forEach(el=>el.addEventListener('input',()=>{const path=el.dataset.path.split('.').map(x=>/^\d+$/.test(x)?Number(x):x);let value=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?null:Number(el.value)):el.value;setValue(path,value)}));document.querySelectorAll('[data-remove]').forEach(el=>el.addEventListener('click',()=>{const [key,i]=el.dataset.remove.split('.');state.config[key].splice(Number(i),1);markDirty();render()}))}
function loadConfig(config,name){state.config=config;state.fileName=name;state.dirty=false;$('#fileName').textContent=name;$('#dirtyState').classList.add('hidden');$('#alert').className='alert hidden';render()}
function validate(){if(!state.config){showAlert('error','Bitte zuerst eine Konfiguration öffnen.');return}const errors=[];if(!state.config.SystemId)errors.push('System-ID fehlt.');for(const key of ['HostConfigurations','Assemblies'])if(!state.config[key])errors.push(`${key} fehlt.`);if(!Array.isArray(state.config.Assemblies)||!state.config.Assemblies.length)errors.push('Mindestens ein Assembly ist erforderlich.');showAlert(errors.length?'error':'success',errors.length?errors.join(' '):'Die Grundstruktur ist gültig. Bitte prüfe gerätespezifische Felder vor dem Start.')}function showAlert(type,msg){const a=$('#alert');a.className=`alert ${type}`;a.textContent=msg}
$('#sectionNav').innerHTML=sections.map(s=>`<button data-section="${s[0]}" class="${s[0]===state.active?'active':''}"><span class="nav-icon">${s[1]}</span>${s[2]}</button>`).join('');document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{state.active=b.dataset.section;document.querySelectorAll('[data-section]').forEach(x=>x.classList.toggle('active',x===b));render()});
$('#openButton').onclick=$('#emptyOpenButton').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{loadConfig(JSON.parse(await f.text()),f.name);showAlert('success',`${f.name} wurde geöffnet.`)}catch(err){showAlert('error',`Die Datei konnte nicht gelesen werden: ${err.message}`)}};
$('#sampleButton').onclick=async()=>{try{const r=await fetch('DevicesConfig/Devices.json');loadConfig(await r.json(),'Devices.json');showAlert('success','Beispielkonfiguration geladen.')}catch(e){showAlert('error','Beispieldatei konnte nicht geladen werden. Bitte öffne eine JSON-Datei.')}};
$('#newButton').onclick=()=>loadConfig({$schema:'./json-devices-schema.json',SystemId:'NewSystem',HostConfigurations:{ImageStorage:{LocalFallbackPath:'ScanBackup',DirectBufferCapacityFrames:50,LocalSpoolBufferCapacityFrames:50},SessionControl:{SessionTimeoutSeconds:30,CleanupIntervalSeconds:1},CameraStreams:{Cameras:[]},DetectorStreams:{Raw:{MemoryBufferCapacityFrames:50,SpoolWriteQueueCapacityFrames:50},Preview:{Enabled:false,Encoder:'Jpeg',Quality:80,MaxFramesPerSecond:30},Lossless:{Enabled:false,Compression:'Zstd',CompressionLevel:3,IncludeChecksum:true}},XFlowProvider:{Enabled:false,Address:'',DelegatedControlAddress:'',DisplayName:'XTom Server',MaxConcurrency:1}},Assemblies:[],Detectors:[],Sources:[],SystemDevices:[],Startup:[]},'Neue DeviceConfig.json');
$('#saveButton').onclick=()=>{if(!state.config)return showAlert('error','Keine Konfiguration zum Speichern geöffnet.');const blob=new Blob([JSON.stringify(state.config,null,2)+'\n'],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=state.fileName||'DeviceConfig.json';a.click();URL.revokeObjectURL(a.href);state.dirty=false;$('#dirtyState').classList.add('hidden');showAlert('success','Konfiguration wurde heruntergeladen.')};
$('#validateButton').onclick=validate;$('#rawButton').onclick=()=>{if(!state.config)return showAlert('error','Keine Konfiguration geöffnet.');$('#rawEditor').value=JSON.stringify(state.config,null,2);$('#rawDialog').showModal()};$('#closeRaw').onclick=$('#cancelRaw').onclick=()=>$('#rawDialog').close();$('#applyRaw').onclick=()=>{try{loadConfig(JSON.parse($('#rawEditor').value),state.fileName);markDirty();$('#rawDialog').close();showAlert('success','Rohdaten übernommen.')}catch(e){showAlert('error',`Ungültiges JSON: ${e.message}`)}};
render();
